### ISSUE TITLE
Some enemy names overflow encounter textbox

### ISSUE THREAD

**Issue by leo60228** [jeffman/Mother2GbaTranslation#115]
One example is the Ramblin' Evil Mushroom.

**Comment by jeffman** [comment]
This one's a real problem and isn't something I anticipated when deciding not to do automatic line breaks. We might have to implement that. Does anyone know how Earthbound handles it?

**Comment by PhoenixBound** [comment]
This should still be possible to handle with manual line breaks, I just haven't gotten around to fixing it yet. It's not the enemy names themselves that overflow, but them plus the text that leads up to them ("You engage the <enemy name>" and such).

It looks like EarthBound only ever attempts to linebreak at these points (will edit once I get a chance to test more thoroughly):

* Before an enemy name (this one may not be explicitly handled since the enemy name has a space before it)
* In between "the " and the enemy name
* After the enemy name

The result looks like:

```
- You encounter the
  Ramblin' Evil Mushroom.
```

**Comment by leo60228** [comment]
I also noticed this happening with "Insane Cultist and its cohort," which might be harder to fix.

**Comment by PhoenixBound** [comment]
The cohorts part is handled in scripting rather than in code so we can just manually use a linebreak if we need to.

And... I should write this down somewhere before I forget. I don't think we've fixed it yet so that all the enemies have the correct intro text? EarthBound changed a few of those, like "The Starman Junior trapped you!" instead of whatever it is in Mother 2. A few overflows may be related to that.

**Comment by leo60228** [comment]
The Mother 3 fan translation had the same problem, and ended up using automatic line breaks for battle text only: https://legendsoflocalization.com/mother-3/chapter1-1/#battle-square

This seems a bit heavy-handed, but it'd definitely fix the problem (and some other quirks of battle text)...

**Comment by Lorenzooone** [comment]
Current results of testing the encounter text with the updated entries...
[test.log](https://github.com/jeffman/Mother2GbaTranslation/files/7876419/test.log)
