### ISSUE TITLE
Carpainter graphics obscure text box

### ISSUE THREAD

**Issue by PhoenixBound** [jeffman/Mother2GbaTranslation#35]
When Carpainter attacks Ness with lightning in the overworld but it's reflected, the text box opens while the lightning is still on screen. When the lightning finally goes away, a portion of the text box is cleared.
![m12-45](https://user-images.githubusercontent.com/13182187/51643302-9ed30980-1f31-11e9-8835-4b189d9d00b7.png)

Possibly related to #34

**Comment by Lorenzooone** [comment]
Issue is that the game starts printing right before the last bolt (the reflected one) is shown.
That corrupts the graphics of the last bolt since it's overwritten and since the game is coded to remove the bolt's graphics, the piece of text that has been already written gets deleted.
Is there a way to make it so it won't print mid-bolt graphics or to make it wait more?
![Cattura](https://user-images.githubusercontent.com/7537905/61184495-a9539d80-a64e-11e9-8988-f002e9040790.PNG)
(Top Japanese, Bottom English)
