### ISSUE TITLE
Strong PSI attacks, like PSI Rockin', against Ness' Nightmare & Giygas disappear after spamming for like four or five times

### ISSUE THREAD

**Issue by John-Enigma** [jeffman/Mother2GbaTranslation#37]
To Ness' Nightmare: In like the fourth or fifth time of throwing PSI Rockin' Yotta at him, my attacks just disappear. And yes, he has PSI Shield Beta on him. I don't know if it's the shield itself, or the hack, but I am not winning this fight. Every time I kept spamming the PSI Rockin' Yotta attack at him, at some point the attacks don't phase him. 

To Giygas: Same thing happens on Giygas' fight in phase two, after Porky stops annoyingly taunting me. This where Giygas starts making his infamous attacks "that I cannot grasp." 

If you want to see what I'm talking about or want to replicate this problems, here's some save states: 

1. In front of Ness' Nightmare (**not during battle**) - https://cdn.discordapp.com/attachments/448360568428953611/540924334957658113/m12.ss1 
2. During Giygas' second phase (where he's constantly saying "You cannot grasp..." for the first time) - https://cdn.discordapp.com/attachments/448360568428953611/540937356593725450/m12.ss3

**Comment by jeffman** [comment]
What's the expected behaviour, i.e. how does Earthbound behave?

**Comment by John-Enigma** [comment]
@jeffman 

The game behaves normally, but every time I try to spam the PSI Rockin attack, none of the animations appear, and it feels like I’m going on a constant loop.

**Comment by John-Enigma** [comment]
^ Also, the attack doesn't affect the boss at all.

**Comment by Lorenzooone** [comment]
This was probably caused by the PP editing code. The game seems to store somewhere the real amount of PPs in battle, so the code which brings the PPs to 999 went into conflct with the game, which went into the negatives.

I know this because I had no trouble whatsoever UNTIL I manually edited 0x3001D8E in order to emulate the effect of the cheat code. As soon as my real PPs went below 0 (not the ones in that address), the game started acting weird as it does in the video.

As a matter of fact, if you store in 0x3001D8E a certain value after you already used a PSI, the game scrolls to the real value after you use another PSI.

Untampered sav in Magicant:
https://cdn.discordapp.com/attachments/431539820133744651/611734084464541823/m12.sav

**Comment by leo60228** [comment]
Shouldn't this be closed? It's a problem with a cheat, not the translation.

**Comment by Lorenzooone** [comment]
We'll re-open this in case it happens without a cheat. Until then, I'll assume what I've written is right and that it's caused by the cheat.
